services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src/GastroLeinefeldeAPI:/app/src/GastroLeinefeldeAPI
    command: dotnet watch run --no-launch-profile