all:
  hosts:
    production:
      ansible_host: "{{ lookup('env', 'PRODUCTION_IP') }}"
      ansible_user: root   # или deploy, но для bootstrap нужен root
      volume_device: /dev/disk/by-id/volume-xxxx   # задаётся из Terraform output
    stage:
      ansible_host: "{{ lookup('env', 'STAGE_IP') }}"
      ansible_user: root